version: '3.8'

services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-app
    environment:
      - OPENROUTESERVICE_API_KEY
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
    restart: always
    env_file:
      - .env
